export default [{
    id: 1,
    name: '铜',
    value: '铜',
    businessRange: '有色金属'
}, {
        id: 2,
        name: '铝',
        value: '铝',
        businessRange: '有色金属'
    }, {
        id: 3,
        name: '铅',
        value: '铅',
        businessRange: '有色金属'
    }, {
        id: 4,
        name: '锌',
        value: '锌',
        businessRange: '有色金属'
    }, {
        id: 6,
        name: '锡',
        value: '锡',
        businessRange: '有色金属'
    }, {
        id: 7,
        name: '镍',
        value: '镍',
        businessRange: '有色金属'
    }, {
        id: 8,
        name: '锰',
        value: '锰',
        businessRange: '有色金属'
    }, {
        id: 9,
        name: '硅',
        value: '硅',
        businessRange: '有色金属'
    }, {
        id: 10,
        name: '钴锂',
        value: '钴锂',
        businessRange: '有色金属'
    }, {
        id: 11,
        name: '锑',
        value: '锑',
        businessRange: '有色金属'
    }, {
        id: 12,
        name: '铟镓锗',
        value: '铟镓锗',
        businessRange: '有色金属'
    }, {
        id: 13,
        name: '钨',
        value: '钨',
        businessRange: '有色金属'
    }, {
        id: 14,
        name: '铋硒碲',
        value: '铋硒碲',
        businessRange: '有色金属'
    },  {
        id: 16,
        name: '小金属',
        value: '小金属',
        businessRange: '小金属'
    }, {
        id: 17,
        name: '贵金属',
        value: '贵金属',
        businessRange: '贵金属'
    }, {
        id: 18,
        name: '稀土',
        value: '稀土',
        businessRange: '化工'
    }, {
        id: 19,
        name: '钢铁',
        value: '钢铁',
        businessRange: '黑色金属'
    }, {
        id: 20,
        name: '废金属',
        value: '废金属',
        businessRange: '黑色金属'
    }, {
        id: 21,
        name: '利源',
        value: '利源',
        businessRange: '化工'
    }];
