export default [{
    id: 1,
    name: '铜',
    value: '铜'
}, {
        id: 2,
        name: '铝',
        value: '铝'
    }, {
        id: 3,
        name: '铅',
        value: '铅'
    }, {
        id: 4,
        name: '锌',
        value: '锌'
    }, {
        id: 6,
        name: '锡',
        value: '锡'
    }, {
        id: 7,
        name: '镍',
        value: '镍'
    }, {
        id: 8,
        name: '锰',
        value: '锰'
    }, {
        id: 9,
        name: '硅',
        value: '硅'
    }, {
        id: 10,
        name: '钴锂',
        value: '钴锂'
    }, {
        id: 11,
        name: '锑',
        value: '锑'
    }, {
        id: 12,
        name: '铟镓锗',
        value: '铟镓锗'
    }, {
        id: 13,
        name: '钨',
        value: '钨'
    }, {
        id: 14,
        name: '铋硒碲',
        value: '铋硒碲'
    }, {
        id: 15,
        name: '钴锂',
        value: '钴锂'
    }, {
        id: 16,
        name: '小金属',
        value: '小金属'
    }, {
        id: 17,
        name: '贵金属',
        value: '贵金属'
    }, {
        id: 18,
        name: '稀土',
        value: '稀土'
    }, {
        id: 19,
        name: '钢铁',
        value: '钢铁'
    }, {
        id: 20,
        name: '废金属',
        value: '废金属'
    }, {
        id: 21,
        name: '利源',
        value: '利源'
    }];
