//filter actions
export const TOGGLE_MULTIPLE_SELECTION = 'TOGGLE_MULTIPLE_SELECTION';
export const TOGGLE_COLLAPSE = 'TOGGLE_COLLAPSE';
export const SELECT_FILTER = 'SELECT_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const CHECK_ITEM  = 'CHECK_ITEM';
export const TYPE_ITEM = 'TYPE_ITEM';
export const TOGGLE_FILTER_LIST = 'TOGGLE_FILTER_LIST';

//chain actions
export const RECEIVE_CHAIN_LIST = 'RECEIVE_CHAIN_LIST';